project_id = "dnllaaspkqqfuuxkvoma"

[functions.show-keys]
verify_jwt = false

[functions.orders-api]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.settings]
verify_jwt = true

[functions.api-keys]
verify_jwt = true

[functions.woocommerce-sync]
verify_jwt = false

[functions.update-woo-prices]
verify_jwt = false

[functions.export-orders]
verify_jwt = false

[functions.import-woocommerce-orders]
verify_jwt = false

[functions.woocommerce-webhook]
verify_jwt = false

[functions.sftp-upload]
verify_jwt = false